### ISSUE TITLE
Dimmable LB-110(EU) and status from LB-110(EU) and HS-110(EU)

### ISSUE THREAD

**Issue by JaneX8** [veetrik/tplink-handler#1]
Hey,
Thanks for this project! It seems to be very helpfull and the first piece of existing code that I get up-and-running.

I tried to test this on an LB-110 (Smart Led Bulb with dimmable soft white l.ight). On and off works fine like:
- node tplink-handler.js -B -J 192.168.1.200 on
- node tplink-handler.js -B -J 192.168.1.200 off

But then it uses the last known dim setting (1% - 100%). I tried to used the Hue option for that but I suppose that's the wrong option here. I would like to dim it between 1% and 100% percent. Can you tell me how you got the right payloads so I can intercept or get them somehow?

I've also tried to get this working on a HS-110 (smart switch with electricity monitor) but it doesn't seem to do anything on that. 

Last thing is that when I run the status info from both devices looks like:

    node tplink-handler.js -B -J 192.168.1.200 ?
    {
     "model":"LB110(EU)",
     "name":"Slaapkamer",
     "dev":"",
     "mac":"",
     "unit":"192.168.1.200",
     "hue":"",
     "state":""
    }

    node tplink-handler.js -B -J 192.168.1.206 ?
    {
     "model":"HS110(EU)",
     "name":"Keuken",
     "dev":"",
     "mac":"",
     "unit":"192.168.1.206",
     "hue":"",
     "state":""
    }

I don't seem to get the current (on/off) state. What could be the problem here?

**Comment by veetrik** [comment]
Hey Kevin,
Glad that you were able to get it running. I wrote this projects for the devices that I currently have, which are the: HS100 (smart switch), LB100 (smart Bulb) & LB130 (smart color bulb).
While the LB100 smart bulb is dimmable, I did not provide an option for
that, but I will look into it.  You can get additional information by using
the following:
 node tplink-handler.js -D 192.168.1.200 ?
The -D switch turns on debugging and will show the full JSON packet that is
returned from the device. I notice above that you are using are for EU devices,
so I added support for this. You need to add the -L=EU switch for these.
I added code for the LB110 & HS110 devices, but was not able to test these.

Regards, Vee

**Comment by JaneX8** [comment]
Ah, that's great! Thanks :) I used the debug method and found some errors. I fixed those bugs. The LB110(EU) does not have the object `sysinfo.light_state.dft_on_state.hue;` and so it throws an error three times on line 99, 106 and 113. 

Changing those three lines to: 
`try { hue = sysinfo.light_state.dft_on_state.hue; } catch(err) { hue = 0; }` supresses that errors at least :). Ultimately you could also remove the "hue" from return info instead of setting it to 0. 

Furthermore (and this is great news)! When I change line 158 from `    	'"on_off":1,"color_temp":0,"hue":'+hue+',"saturation":100}}}}';` to `    	'"on_off":1,"color_temp":0,"brightness":'+hue+',"saturation":100}}}}';`

I'm able to set the brightness between 1-100.
- 10% brightness: `node tplink-handler.js -B -L=EU -H 192.168.1.200 10`
- 100% brightness: `node tplink-handler.js -B -L=EU -H 192.168.1.200 100` 

I'm aware I misused the hue function for that test :P It could be nice to make a brightness adjust option or function using the above suggestions. If you want I can work it out and send a pull request later. Or feel free to use it as you like. 

Also the status request is now correctly working. `?` will now tell me wether it's on or off correctly.

**Comment by veetrik** [comment]
Thanks Calico90, I incorporated your suggestions into the latest version.

**Comment by veetrik** [comment]
This issue is ow closed
