### ISSUE TITLE
HS-110(EU) - Energy info

### ISSUE THREAD

**Issue by JaneX8** [veetrik/tplink-handler#2]
Hey,
I can confirm that I'm able to enable and disable the smart plug HS110(EU) with your script. Using: 

`node tplink-handler.js -L=EU -D 192.168.1.206 off` and `node tplink-handler.js -L=EU -D 192.168.1.206 on` but I cannot seem to get info about the energy monitoring. The systeminfo from command `node tplink-handler.js -L=EU -D 192.168.1.206 ?` shows a lot but I don't see energy info.

     D=true B=false T=500 J=false C=false H=false L=EU
     unit=192.168.1.206 addr=192.168.1.206 cmd=?
     get state request sent to 192.168.1.206

    {"system":{"get_sysinfo":{"err_code":0,"sw_ver":"1.1.0 Build 160503 Rel.144605","hw_ver":"1.0","type":"IOT.SMARTPLUGSWITCH","model":"HS110(EU)","mac":"XXXXXXXXXXXXXX","deviceId":"XXXXXXXXXXXXXX","hwId":"XXXXXXXXXXXXXX0B2EB5","fwId":"XXXXXXXXXXXXXX","oemId":"XXXXXXXXXXXXXXXXXXX","alias":"XXXXXXXXXXXXXX","dev_name":"Wi-Fi Smart Plug With Energy Monitoring","icon_hash":"","relay_state":1,"on_time":5,"active_mode":"schedule","feature":"TIM:ENE","updating":0,"rssi":-50,"led_off":0,"latitude":XXXXXXXXXXXXXX,"longitude":XXXXXXXXXXXXXX}}} from 192.168.1.206
    192.168.1.206=1

**Comment by veetrik** [comment]
It looks like the get_sysinfo does not return this information. My guess would be that there is another function call that must be made to get this additional info.

**Comment by JaneX8** [comment]
I found this:

https://github.com/softScheck/tplink-smartplug/blob/master/tplink-smarthome-commands.txt and this https://www.softscheck.com/en/reverse-engineering-tp-link-hs110/. 

The emeter object contains and returns electricity usage info on the HS-110 but not from my LB-110.
